name: Full Flutter CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build (local testing only, not for upstream CI)"
        type: choice
        default: all
        options:
          - all
          - android
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    permissions:
      contents: write
    with:
      upload-artifact: ${{ inputs.platform == 'android' }}
      platform: ${{ inputs.platform || 'all' }}
